name: visage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  http: ^1.4.0
  web: ^1.1.1

  flutter_riverpod: ^2.6.1  # 업데이트 제외 (요청)
 
  nyx_kernel:
    path: ../nyx_kernel
  file_picker: ^10.3.10
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
